---
- name: Add mongo ppa key
  become: yes
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-3.4.asc
    state: present
- name: Add mongo sources list
  become: yes
  copy:
    dest: /etc/apt/sources.list.d/mongodb.list
    content: >
        deb https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse
- name: Install mongo
  become: yes
  apt:
    name: mongodb-org
    state: latest
    update_cache: yes
  notify:
      - restart mongo
- name: Enable mongo service
  become: yes
  systemd:
    name: mongod.service
    enabled: yes
