---
- name: Add mongo ppa key
  become: yes
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: EA312927
    state: present
- name: Add mongo sources list
  become: yes
  lineinfile: >
    line="deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse"
    dest=/etc/apt/sources.list.d/mongodb.list
    state=present
    create=yes
- name: Install mongo
  become: yes
  apt:
    name: mongodb-org
    state: latest
    update_cache: yes
  notify:
      - restart mongo
- name: Enable mongo service
  become: yes
  systemd:
    name: mongod.service
    enabled: yes
